name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        macos-version: [macos-13, macos-14, macos-15]
        node-version: [22.x]
    runs-on: ${{ matrix.macos-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: package.json
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run test
